import mongoose from "mongoose";


const orderSchema=new mongoose.Schema({
     orderId:{
        type:String,
        unique:true,
     },
     customer:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Customer",
        required:true
     },
      deliveryPartner:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"DeliveryPartner",
     },
     branch:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Branch",
        required:true
     },
     items:[
        {
            id:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"Product",
                required:true,
            },
            item:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"Product",
                required:true,
            },
            count:{type:Number,required:true},
        }
     ],
     deliveryLocation:{
        latitude:{type:Number,required:true},
        longitude:{type:Number,required:true},
        address:{type:String},
     },
     pickupLocation:{
        latitude:{type:Number,required:true},
        longitude:{type:Number,required:true},
        address:{type:String},
     },
     deliveryPersonLocation:{
        latitude:{type:Number,required:true},
        longitude:{type:Number,required:true},
        address:{type:String},
     },

     status:{
        type:String,
        enum:["available","confirmed","arriving","delivered","cancelled"],
     },
     totalPrice:{type:String,required:true},
     createdAt:{type:Date,default:Date.now()},
     updatedAt:{type:Date,default:Date.now()}
})